server:
  port: 9090
  forward-headers-strategy: framework

spring:
  application:
    name: micro-service-course
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coursesDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZooServer: http://localhost:8761/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: TRACE

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
  cache:
    disabled: true