server:
  port: 8080

spring:
  application:
    name: micro-service-api-getewa
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/**
          filters:
            - AuthenticationFilter
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/course/**
          filters:
            - AuthenticationFilter
eureka:
  client:
    register-with-eureka: false